version: '2.2'

services:
  sinbox-analytics:
    image: cubejs/cube:v0.29.34
    ports:
      # It's better to use random port binding for 4000/3000 ports
      # without it you will not able to start multiple projects inside docker
      - 14000:14000 # Cube.js API and Developer Playground
      - 3000:3000 # Dashboard app, if created
    env_file: .env
    volumes:
      - .:/cube/conf
      # We ignore Cube.js deps, because they are built-in inside the official Docker image
      - .empty:/cube/conf/node_modules/@cubejs-backend/
  sinbox-postgres:
    image: postgres:12.2
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - sinbox:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
  sinbox-redis:
    image: redis:6.0.1-alpine
    volumes:
      - sinbox:/data
    restart: always
    ports:
      - 6379:6379
  mongo:
    image: mongo:4.2.5
    restart: always
    volumes:
      - datadb:/data/db
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
    ports:
      - 27017:27017
volumes:
  sinbox:
  datadb:
